package com.straw.lession.physical.vo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CLASS_INFO".
 */
@Entity
public class ClassInfo {

    @Id
    private Long id;
    private String code;
    private String name;
    private String type;
    private Integer totalNum;
    private Long classIdR;
    private Long instituteId;
    private Long instituteIdR;
    private Long loginId;

    @Generated
    public ClassInfo() {
    }

    public ClassInfo(Long id) {
        this.id = id;
    }

    @Generated
    public ClassInfo(Long id, String code, String name, String type, Integer totalNum, Long classIdR, Long instituteId, Long instituteIdR, Long loginId) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.type = type;
        this.totalNum = totalNum;
        this.classIdR = classIdR;
        this.instituteId = instituteId;
        this.instituteIdR = instituteIdR;
        this.loginId = loginId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getTotalNum() {
        return totalNum;
    }

    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    public Long getClassIdR() {
        return classIdR;
    }

    public void setClassIdR(Long classIdR) {
        this.classIdR = classIdR;
    }

    public Long getInstituteId() {
        return instituteId;
    }

    public void setInstituteId(Long instituteId) {
        this.instituteId = instituteId;
    }

    public Long getInstituteIdR() {
        return instituteIdR;
    }

    public void setInstituteIdR(Long instituteIdR) {
        this.instituteIdR = instituteIdR;
    }

    public Long getLoginId() {
        return loginId;
    }

    public void setLoginId(Long loginId) {
        this.loginId = loginId;
    }

}
