package com.straw.lession.physical.vo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COURSE_DEFINE".
 */
@Entity
public class CourseDefine {

    @Id
    private Long id;
    private String code;
    private String name;
    private String type;
    private Long instituteId;
    private Long classId;
    private Long teacherId;
    private Integer weekDay;
    private java.util.Date date;
    private Integer seq;
    private String location;
    private java.util.Date startTime;
    private java.util.Date endTime;
    private Integer useOnce;

    @Generated
    public CourseDefine() {
    }

    public CourseDefine(Long id) {
        this.id = id;
    }

    @Generated
    public CourseDefine(Long id, String code, String name, String type, Long instituteId, Long classId, Long teacherId, Integer weekDay, java.util.Date date, Integer seq, String location, java.util.Date startTime, java.util.Date endTime, Integer useOnce) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.type = type;
        this.instituteId = instituteId;
        this.classId = classId;
        this.teacherId = teacherId;
        this.weekDay = weekDay;
        this.date = date;
        this.seq = seq;
        this.location = location;
        this.startTime = startTime;
        this.endTime = endTime;
        this.useOnce = useOnce;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getInstituteId() {
        return instituteId;
    }

    public void setInstituteId(Long instituteId) {
        this.instituteId = instituteId;
    }

    public Long getClassId() {
        return classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public Long getTeacherId() {
        return teacherId;
    }

    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    public Integer getWeekDay() {
        return weekDay;
    }

    public void setWeekDay(Integer weekDay) {
        this.weekDay = weekDay;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getSeq() {
        return seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public java.util.Date getStartTime() {
        return startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getEndTime() {
        return endTime;
    }

    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
    }

    public Integer getUseOnce() {
        return useOnce;
    }

    public void setUseOnce(Integer useOnce) {
        this.useOnce = useOnce;
    }

}
