package com.straw.lession.physical.vo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INSTITUTE".
 */
@Entity
public class Institute {

    @Id
    private Long id;
    private String code;
    private String name;
    private Long instituteIdR;
    private Long loginId;

    @Generated
    public Institute() {
    }

    public Institute(Long id) {
        this.id = id;
    }

    @Generated
    public Institute(Long id, String code, String name, Long instituteIdR, Long loginId) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.instituteIdR = instituteIdR;
        this.loginId = loginId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getInstituteIdR() {
        return instituteIdR;
    }

    public void setInstituteIdR(Long instituteIdR) {
        this.instituteIdR = instituteIdR;
    }

    public Long getLoginId() {
        return loginId;
    }

    public void setLoginId(Long loginId) {
        this.loginId = loginId;
    }

}
