package com.straw.lession.physical.vo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STUDENT".
 */
@Entity
public class Student {

    @Id
    private Long id;
    private String code;
    private String name;
    private Integer gender;
    private java.util.Date birthday;
    private Long classId;
    private Long classIdR;
    private Long studentIdR;
    private Long loginId;

    @Generated
    public Student() {
    }

    public Student(Long id) {
        this.id = id;
    }

    @Generated
    public Student(Long id, String code, String name, Integer gender, java.util.Date birthday, Long classId, Long classIdR, Long studentIdR, Long loginId) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.gender = gender;
        this.birthday = birthday;
        this.classId = classId;
        this.classIdR = classIdR;
        this.studentIdR = studentIdR;
        this.loginId = loginId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    public Long getClassId() {
        return classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public Long getClassIdR() {
        return classIdR;
    }

    public void setClassIdR(Long classIdR) {
        this.classIdR = classIdR;
    }

    public Long getStudentIdR() {
        return studentIdR;
    }

    public void setStudentIdR(Long studentIdR) {
        this.studentIdR = studentIdR;
    }

    public Long getLoginId() {
        return loginId;
    }

    public void setLoginId(Long loginId) {
        this.loginId = loginId;
    }

}
