package com.straw.lession.physical.vo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEACHER".
 */
@Entity
public class Teacher {

    @Id
    private Long id;
    private String name;
    private String mobile;
    private java.util.Date last_login_time;
    private Long teacherIdR;

    @Generated
    public Teacher() {
    }

    public Teacher(Long id) {
        this.id = id;
    }

    @Generated
    public Teacher(Long id, String name, String mobile, java.util.Date last_login_time, Long teacherIdR) {
        this.id = id;
        this.name = name;
        this.mobile = mobile;
        this.last_login_time = last_login_time;
        this.teacherIdR = teacherIdR;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public java.util.Date getLast_login_time() {
        return last_login_time;
    }

    public void setLast_login_time(java.util.Date last_login_time) {
        this.last_login_time = last_login_time;
    }

    public Long getTeacherIdR() {
        return teacherIdR;
    }

    public void setTeacherIdR(Long teacherIdR) {
        this.teacherIdR = teacherIdR;
    }

}
