package com.straw.lession.physical.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.straw.lession.physical.vo.db.Institute;

import com.straw.lession.physical.vo.db.ClassInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLASS_INFO".
*/
public class ClassInfoDao extends AbstractDao<ClassInfo, Long> {

    public static final String TABLENAME = "CLASS_INFO";

    /**
     * Properties of entity ClassInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Code = new Property(0, String.class, "code", false, "CODE");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
        public final static Property TotalNum = new Property(3, Integer.class, "totalNum", false, "TOTAL_NUM");
        public final static Property ClassIdR = new Property(4, Long.class, "classIdR", true, "CLASS_ID_R");
        public final static Property IsDel = new Property(5, Integer.class, "isDel", false, "IS_DEL");
        public final static Property InstituteIdR = new Property(6, Long.class, "instituteIdR", false, "INSTITUTE_ID_R");
    };

    private DaoSession daoSession;

    private Query<ClassInfo> institute_ClassesQuery;

    public ClassInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ClassInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLASS_INFO\" (" + //
                "\"CODE\" TEXT," + // 0: code
                "\"NAME\" TEXT," + // 1: name
                "\"TYPE\" TEXT," + // 2: type
                "\"TOTAL_NUM\" INTEGER," + // 3: totalNum
                "\"CLASS_ID_R\" INTEGER PRIMARY KEY ," + // 4: classIdR
                "\"IS_DEL\" INTEGER," + // 5: isDel
                "\"INSTITUTE_ID_R\" INTEGER);"); // 6: instituteIdR
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLASS_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ClassInfo entity) {
        stmt.clearBindings();
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(1, code);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        Integer totalNum = entity.getTotalNum();
        if (totalNum != null) {
            stmt.bindLong(4, totalNum);
        }
 
        Long classIdR = entity.getClassIdR();
        if (classIdR != null) {
            stmt.bindLong(5, classIdR);
        }
 
        Integer isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(6, isDel);
        }
 
        Long instituteIdR = entity.getInstituteIdR();
        if (instituteIdR != null) {
            stmt.bindLong(7, instituteIdR);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ClassInfo entity) {
        stmt.clearBindings();
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(1, code);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        Integer totalNum = entity.getTotalNum();
        if (totalNum != null) {
            stmt.bindLong(4, totalNum);
        }
 
        Long classIdR = entity.getClassIdR();
        if (classIdR != null) {
            stmt.bindLong(5, classIdR);
        }
 
        Integer isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(6, isDel);
        }
 
        Long instituteIdR = entity.getInstituteIdR();
        if (instituteIdR != null) {
            stmt.bindLong(7, instituteIdR);
        }
    }

    @Override
    protected final void attachEntity(ClassInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4);
    }    

    @Override
    public ClassInfo readEntity(Cursor cursor, int offset) {
        ClassInfo entity = new ClassInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // code
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // totalNum
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // classIdR
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // isDel
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // instituteIdR
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ClassInfo entity, int offset) {
        entity.setCode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTotalNum(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setClassIdR(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setIsDel(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setInstituteIdR(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ClassInfo entity, long rowId) {
        entity.setClassIdR(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ClassInfo entity) {
        if(entity != null) {
            return entity.getClassIdR();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "classes" to-many relationship of Institute. */
    public List<ClassInfo> _queryInstitute_Classes(Long instituteIdR) {
        synchronized (this) {
            if (institute_ClassesQuery == null) {
                QueryBuilder<ClassInfo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.InstituteIdR.eq(null));
                institute_ClassesQuery = queryBuilder.build();
            }
        }
        Query<ClassInfo> query = institute_ClassesQuery.forCurrentThread();
        query.setParameter(0, instituteIdR);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getInstituteDao().getAllColumns());
            builder.append(" FROM CLASS_INFO T");
            builder.append(" LEFT JOIN INSTITUTE T0 ON T.\"INSTITUTE_ID_R\"=T0.\"INSTITUTE_ID_R\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ClassInfo loadCurrentDeep(Cursor cursor, boolean lock) {
        ClassInfo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Institute institute = loadCurrentOther(daoSession.getInstituteDao(), cursor, offset);
        entity.setInstitute(institute);

        return entity;    
    }

    public ClassInfo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ClassInfo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ClassInfo> list = new ArrayList<ClassInfo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ClassInfo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ClassInfo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
