package com.straw.lession.physical.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.straw.lession.physical.vo.db.CourseDefine;

import com.straw.lession.physical.vo.db.Course;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COURSE".
*/
public class CourseDao extends AbstractDao<Course, Long> {

    public static final String TABLENAME = "COURSE";

    /**
     * Properties of entity Course.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LoginId = new Property(1, Long.class, "loginId", false, "LOGIN_ID");
        public final static Property UseOnce = new Property(2, Integer.class, "useOnce", false, "USE_ONCE");
        public final static Property CourseDefineId = new Property(3, Long.class, "courseDefineId", false, "COURSE_DEFINE_ID");
    };

    private DaoSession daoSession;


    public CourseDao(DaoConfig config) {
        super(config);
    }
    
    public CourseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COURSE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LOGIN_ID\" INTEGER," + // 1: loginId
                "\"USE_ONCE\" INTEGER," + // 2: useOnce
                "\"COURSE_DEFINE_ID\" INTEGER);"); // 3: courseDefineId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COURSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Course entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long loginId = entity.getLoginId();
        if (loginId != null) {
            stmt.bindLong(2, loginId);
        }
 
        Integer useOnce = entity.getUseOnce();
        if (useOnce != null) {
            stmt.bindLong(3, useOnce);
        }
 
        Long courseDefineId = entity.getCourseDefineId();
        if (courseDefineId != null) {
            stmt.bindLong(4, courseDefineId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Course entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long loginId = entity.getLoginId();
        if (loginId != null) {
            stmt.bindLong(2, loginId);
        }
 
        Integer useOnce = entity.getUseOnce();
        if (useOnce != null) {
            stmt.bindLong(3, useOnce);
        }
 
        Long courseDefineId = entity.getCourseDefineId();
        if (courseDefineId != null) {
            stmt.bindLong(4, courseDefineId);
        }
    }

    @Override
    protected final void attachEntity(Course entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Course readEntity(Cursor cursor, int offset) {
        Course entity = new Course( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // loginId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // useOnce
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // courseDefineId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Course entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLoginId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setUseOnce(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCourseDefineId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Course entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Course entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCourseDefineDao().getAllColumns());
            builder.append(" FROM COURSE T");
            builder.append(" LEFT JOIN COURSE_DEFINE T0 ON T.\"COURSE_DEFINE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Course loadCurrentDeep(Cursor cursor, boolean lock) {
        Course entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CourseDefine courseDefine = loadCurrentOther(daoSession.getCourseDefineDao(), cursor, offset);
        entity.setCourseDefine(courseDefine);

        return entity;    
    }

    public Course loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Course> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Course> list = new ArrayList<Course>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Course> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Course> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
