package com.straw.lession.physical.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.straw.lession.physical.vo.db.CourseDefine;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COURSE_DEFINE".
*/
public class CourseDefineDao extends AbstractDao<CourseDefine, Long> {

    public static final String TABLENAME = "COURSE_DEFINE";

    /**
     * Properties of entity CourseDefine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Code = new Property(1, String.class, "code", false, "CODE");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property InstituteId = new Property(4, Long.class, "instituteId", false, "INSTITUTE_ID");
        public final static Property InstituteIdR = new Property(5, Long.class, "instituteIdR", false, "INSTITUTE_ID_R");
        public final static Property ClassId = new Property(6, Long.class, "classId", false, "CLASS_ID");
        public final static Property ClassIdR = new Property(7, Long.class, "classIdR", false, "CLASS_ID_R");
        public final static Property TeacherId = new Property(8, Long.class, "teacherId", false, "TEACHER_ID");
        public final static Property WeekDay = new Property(9, Integer.class, "weekDay", false, "WEEK_DAY");
        public final static Property Date = new Property(10, java.util.Date.class, "date", false, "DATE");
        public final static Property Seq = new Property(11, Integer.class, "seq", false, "SEQ");
        public final static Property Location = new Property(12, String.class, "location", false, "LOCATION");
        public final static Property StartTime = new Property(13, java.util.Date.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(14, java.util.Date.class, "endTime", false, "END_TIME");
        public final static Property UseOnce = new Property(15, Integer.class, "useOnce", false, "USE_ONCE");
        public final static Property CourseDefineIdR = new Property(16, Long.class, "courseDefineIdR", false, "COURSE_DEFINE_ID_R");
        public final static Property LoginId = new Property(17, Long.class, "loginId", false, "LOGIN_ID");
    };


    public CourseDefineDao(DaoConfig config) {
        super(config);
    }
    
    public CourseDefineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COURSE_DEFINE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CODE\" TEXT," + // 1: code
                "\"NAME\" TEXT," + // 2: name
                "\"TYPE\" TEXT," + // 3: type
                "\"INSTITUTE_ID\" INTEGER," + // 4: instituteId
                "\"INSTITUTE_ID_R\" INTEGER," + // 5: instituteIdR
                "\"CLASS_ID\" INTEGER," + // 6: classId
                "\"CLASS_ID_R\" INTEGER," + // 7: classIdR
                "\"TEACHER_ID\" INTEGER," + // 8: teacherId
                "\"WEEK_DAY\" INTEGER," + // 9: weekDay
                "\"DATE\" INTEGER," + // 10: date
                "\"SEQ\" INTEGER," + // 11: seq
                "\"LOCATION\" TEXT," + // 12: location
                "\"START_TIME\" INTEGER," + // 13: startTime
                "\"END_TIME\" INTEGER," + // 14: endTime
                "\"USE_ONCE\" INTEGER," + // 15: useOnce
                "\"COURSE_DEFINE_ID_R\" INTEGER," + // 16: courseDefineIdR
                "\"LOGIN_ID\" INTEGER);"); // 17: loginId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COURSE_DEFINE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CourseDefine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(2, code);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        Long instituteId = entity.getInstituteId();
        if (instituteId != null) {
            stmt.bindLong(5, instituteId);
        }
 
        Long instituteIdR = entity.getInstituteIdR();
        if (instituteIdR != null) {
            stmt.bindLong(6, instituteIdR);
        }
 
        Long classId = entity.getClassId();
        if (classId != null) {
            stmt.bindLong(7, classId);
        }
 
        Long classIdR = entity.getClassIdR();
        if (classIdR != null) {
            stmt.bindLong(8, classIdR);
        }
 
        Long teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindLong(9, teacherId);
        }
 
        Integer weekDay = entity.getWeekDay();
        if (weekDay != null) {
            stmt.bindLong(10, weekDay);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(11, date.getTime());
        }
 
        Integer seq = entity.getSeq();
        if (seq != null) {
            stmt.bindLong(12, seq);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(13, location);
        }
 
        java.util.Date startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(14, startTime.getTime());
        }
 
        java.util.Date endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(15, endTime.getTime());
        }
 
        Integer useOnce = entity.getUseOnce();
        if (useOnce != null) {
            stmt.bindLong(16, useOnce);
        }
 
        Long courseDefineIdR = entity.getCourseDefineIdR();
        if (courseDefineIdR != null) {
            stmt.bindLong(17, courseDefineIdR);
        }
 
        Long loginId = entity.getLoginId();
        if (loginId != null) {
            stmt.bindLong(18, loginId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CourseDefine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(2, code);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        Long instituteId = entity.getInstituteId();
        if (instituteId != null) {
            stmt.bindLong(5, instituteId);
        }
 
        Long instituteIdR = entity.getInstituteIdR();
        if (instituteIdR != null) {
            stmt.bindLong(6, instituteIdR);
        }
 
        Long classId = entity.getClassId();
        if (classId != null) {
            stmt.bindLong(7, classId);
        }
 
        Long classIdR = entity.getClassIdR();
        if (classIdR != null) {
            stmt.bindLong(8, classIdR);
        }
 
        Long teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindLong(9, teacherId);
        }
 
        Integer weekDay = entity.getWeekDay();
        if (weekDay != null) {
            stmt.bindLong(10, weekDay);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(11, date.getTime());
        }
 
        Integer seq = entity.getSeq();
        if (seq != null) {
            stmt.bindLong(12, seq);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(13, location);
        }
 
        java.util.Date startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(14, startTime.getTime());
        }
 
        java.util.Date endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(15, endTime.getTime());
        }
 
        Integer useOnce = entity.getUseOnce();
        if (useOnce != null) {
            stmt.bindLong(16, useOnce);
        }
 
        Long courseDefineIdR = entity.getCourseDefineIdR();
        if (courseDefineIdR != null) {
            stmt.bindLong(17, courseDefineIdR);
        }
 
        Long loginId = entity.getLoginId();
        if (loginId != null) {
            stmt.bindLong(18, loginId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CourseDefine readEntity(Cursor cursor, int offset) {
        CourseDefine entity = new CourseDefine( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // code
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // instituteId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // instituteIdR
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // classId
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // classIdR
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // teacherId
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // weekDay
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // date
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // seq
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // location
            cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)), // startTime
            cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)), // endTime
            cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15), // useOnce
            cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16), // courseDefineIdR
            cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17) // loginId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CourseDefine entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setInstituteId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setInstituteIdR(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setClassId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setClassIdR(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setTeacherId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setWeekDay(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setDate(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setSeq(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setLocation(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setStartTime(cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)));
        entity.setEndTime(cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)));
        entity.setUseOnce(cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15));
        entity.setCourseDefineIdR(cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16));
        entity.setLoginId(cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CourseDefine entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CourseDefine entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
