package com.straw.lession.physical.db;

import com.straw.lession.physical.vo.db.ClassInfo;
import com.straw.lession.physical.vo.db.CourseDefine;
import com.straw.lession.physical.vo.db.Institute;
import com.straw.lession.physical.vo.db.Student;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseDefineDaoConfig;
    private final DaoConfig classInfoDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig instituteDaoConfig;

    private final CourseDefineDao courseDefineDao;
    private final ClassInfoDao classInfoDao;
    private final StudentDao studentDao;
    private final InstituteDao instituteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseDefineDaoConfig = daoConfigMap.get(CourseDefineDao.class).clone();
        courseDefineDaoConfig.initIdentityScope(type);

        classInfoDaoConfig = daoConfigMap.get(ClassInfoDao.class).clone();
        classInfoDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        instituteDaoConfig = daoConfigMap.get(InstituteDao.class).clone();
        instituteDaoConfig.initIdentityScope(type);

        courseDefineDao = new CourseDefineDao(courseDefineDaoConfig, this);
        classInfoDao = new ClassInfoDao(classInfoDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        instituteDao = new InstituteDao(instituteDaoConfig, this);

        registerDao(CourseDefine.class, courseDefineDao);
        registerDao(ClassInfo.class, classInfoDao);
        registerDao(Student.class, studentDao);
        registerDao(Institute.class, instituteDao);
    }
    
    public void clear() {
        courseDefineDaoConfig.getIdentityScope().clear();
        classInfoDaoConfig.getIdentityScope().clear();
        studentDaoConfig.getIdentityScope().clear();
        instituteDaoConfig.getIdentityScope().clear();
    }

    public CourseDefineDao getCourseDefineDao() {
        return courseDefineDao;
    }

    public ClassInfoDao getClassInfoDao() {
        return classInfoDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public InstituteDao getInstituteDao() {
        return instituteDao;
    }

}
