package com.straw.lession.physical.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.straw.lession.physical.vo.db.Course;
import com.straw.lession.physical.vo.db.Student;

import com.straw.lession.physical.vo.db.StudentDevice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STUDENT_DEVICE".
*/
public class StudentDeviceDao extends AbstractDao<StudentDevice, Long> {

    public static final String TABLENAME = "STUDENT_DEVICE";

    /**
     * Properties of entity StudentDevice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DeviceNo = new Property(1, String.class, "deviceNo", false, "DEVICE_NO");
        public final static Property BindTime = new Property(2, java.util.Date.class, "bindTime", false, "BIND_TIME");
        public final static Property TeacherIdR = new Property(3, Long.class, "teacherIdR", false, "TEACHER_ID_R");
        public final static Property IsUploaded = new Property(4, Boolean.class, "isUploaded", false, "IS_UPLOADED");
        public final static Property CourseDefineIdR = new Property(5, Long.class, "courseDefineIdR", false, "COURSE_DEFINE_ID_R");
        public final static Property CourseId = new Property(6, Long.class, "courseId", false, "COURSE_ID");
        public final static Property StudentIdR = new Property(7, Long.class, "studentIdR", false, "STUDENT_ID_R");
    };

    private DaoSession daoSession;


    public StudentDeviceDao(DaoConfig config) {
        super(config);
    }
    
    public StudentDeviceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STUDENT_DEVICE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DEVICE_NO\" TEXT," + // 1: deviceNo
                "\"BIND_TIME\" INTEGER," + // 2: bindTime
                "\"TEACHER_ID_R\" INTEGER," + // 3: teacherIdR
                "\"IS_UPLOADED\" INTEGER," + // 4: isUploaded
                "\"COURSE_DEFINE_ID_R\" INTEGER," + // 5: courseDefineIdR
                "\"COURSE_ID\" INTEGER," + // 6: courseId
                "\"STUDENT_ID_R\" INTEGER);"); // 7: studentIdR
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STUDENT_DEVICE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StudentDevice entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String deviceNo = entity.getDeviceNo();
        if (deviceNo != null) {
            stmt.bindString(2, deviceNo);
        }
 
        java.util.Date bindTime = entity.getBindTime();
        if (bindTime != null) {
            stmt.bindLong(3, bindTime.getTime());
        }
 
        Long teacherIdR = entity.getTeacherIdR();
        if (teacherIdR != null) {
            stmt.bindLong(4, teacherIdR);
        }
 
        Boolean isUploaded = entity.getIsUploaded();
        if (isUploaded != null) {
            stmt.bindLong(5, isUploaded ? 1L: 0L);
        }
 
        Long courseDefineIdR = entity.getCourseDefineIdR();
        if (courseDefineIdR != null) {
            stmt.bindLong(6, courseDefineIdR);
        }
 
        Long courseId = entity.getCourseId();
        if (courseId != null) {
            stmt.bindLong(7, courseId);
        }
 
        Long studentIdR = entity.getStudentIdR();
        if (studentIdR != null) {
            stmt.bindLong(8, studentIdR);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StudentDevice entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String deviceNo = entity.getDeviceNo();
        if (deviceNo != null) {
            stmt.bindString(2, deviceNo);
        }
 
        java.util.Date bindTime = entity.getBindTime();
        if (bindTime != null) {
            stmt.bindLong(3, bindTime.getTime());
        }
 
        Long teacherIdR = entity.getTeacherIdR();
        if (teacherIdR != null) {
            stmt.bindLong(4, teacherIdR);
        }
 
        Boolean isUploaded = entity.getIsUploaded();
        if (isUploaded != null) {
            stmt.bindLong(5, isUploaded ? 1L: 0L);
        }
 
        Long courseDefineIdR = entity.getCourseDefineIdR();
        if (courseDefineIdR != null) {
            stmt.bindLong(6, courseDefineIdR);
        }
 
        Long courseId = entity.getCourseId();
        if (courseId != null) {
            stmt.bindLong(7, courseId);
        }
 
        Long studentIdR = entity.getStudentIdR();
        if (studentIdR != null) {
            stmt.bindLong(8, studentIdR);
        }
    }

    @Override
    protected final void attachEntity(StudentDevice entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StudentDevice readEntity(Cursor cursor, int offset) {
        StudentDevice entity = new StudentDevice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // deviceNo
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // bindTime
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // teacherIdR
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isUploaded
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // courseDefineIdR
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // courseId
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // studentIdR
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StudentDevice entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBindTime(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setTeacherIdR(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIsUploaded(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setCourseDefineIdR(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setCourseId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setStudentIdR(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StudentDevice entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StudentDevice entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCourseDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getStudentDao().getAllColumns());
            builder.append(" FROM STUDENT_DEVICE T");
            builder.append(" LEFT JOIN COURSE T0 ON T.\"COURSE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN STUDENT T1 ON T.\"STUDENT_ID_R\"=T1.\"STUDENT_ID_R\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected StudentDevice loadCurrentDeep(Cursor cursor, boolean lock) {
        StudentDevice entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Course course = loadCurrentOther(daoSession.getCourseDao(), cursor, offset);
        entity.setCourse(course);
        offset += daoSession.getCourseDao().getAllColumns().length;

        Student student = loadCurrentOther(daoSession.getStudentDao(), cursor, offset);
        entity.setStudent(student);

        return entity;    
    }

    public StudentDevice loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<StudentDevice> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<StudentDevice> list = new ArrayList<StudentDevice>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<StudentDevice> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<StudentDevice> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
